### ISSUE TITLE
Backend wont connect

### ISSUE THREAD

**Issue by lettawi** [MustardWallet/MustardWalletLTC#14]
Backend is not connecting, and I am unable to send my Litecoins.

**Comment by gabrielkrieger** [comment]
Thank you for reporting ! Indeed - the backend went out of memory again , it just took a lot longer for the issue to occur since now that we have more RAM in the machine . I've restarted the backend . A permanent fix would be to re-sync with the upstream Wasabi backend , assuming the leak has been fixed there ...
